(deftheme mgualt-solarized-dark
  "Created 2013-08-13.")

(custom-theme-set-variables
 'mgualt-solarized-dark
 '(ansi-color-names-vector ["#002b36" "#dc322f" "#859900" "#b58900" "#268bd2" "#d33682" "#2aa198" "#839496"])
 '(compilation-message-face (quote default)))

(custom-theme-set-faces
 'mgualt-solarized-dark
 '(button ((t (:underline t))))
 '(shadow ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(match ((((class color) (min-colors 89)) (:background "#073642" :foreground "#93a1a1" :weight bold))))
 '(cursor ((((class color) (min-colors 89)) (:foreground "#002b36" :background "#839496" :inverse-video t))))
 '(mouse ((((class color) (min-colors 89)) (:foreground "#002b36" :background "#839496" :inverse-video t))))
 '(escape-glyph-face ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(fringe ((((class color) (min-colors 89)) (:foreground "#839496" :background "#002b36"))))
 '(highlight ((((class color) (min-colors 89)) (:background "#073642"))))
 '(link ((((class color) (min-colors 89)) (:foreground "#b58900" :underline t :weight bold))))
 '(link-visited ((((class color) (min-colors 89)) (:foreground "#b58900" :underline t :weight normal))))
 '(success ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(error ((((class color) (min-colors 89)) (:foreground "#cb4b16"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:foreground "#002b36" :background "#b58900" :weight normal))))
 '(escape-glyph ((((class color) (min-colors 89)) (:foreground "#6c71c4"))))
 '(compilation-column-face ((((class color) (min-colors 89)) (:foreground "#2aa198" :underline nil))))
 '(compilation-column-number ((((class color) (min-colors 89)) (:inherit font-lock-doc-face :foreground "#2aa198" :underline nil))))
 '(compilation-enter-directory-face ((((class color) (min-colors 89)) (:foreground "#859900" :underline nil))))
 '(compilation-error ((((class color) (min-colors 89)) (:inherit error :underline nil))))
 '(compilation-error-face ((((class color) (min-colors 89)) (:foreground "#dc322f" : :underline nil))))
 '(compilation-face ((((class color) (min-colors 89)) (:foreground "#839496" :underline nil))))
 '(compilation-info ((((class color) (min-colors 89)) (:foreground "#586e75" :underline nil :bold nil))))
 '(compilation-info-face ((((class color) (min-colors 89)) (:foreground "#268bd2" :underline nil))))
 '(compilation-leave-directory-face ((((class color) (min-colors 89)) (:foreground "#859900" :underline nil))))
 '(compilation-line-face ((((class color) (min-colors 89)) (:foreground "#859900" :underline nil))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:foreground "#859900" :underline nil))))
 '(compilation-warning ((((class color) (min-colors 89)) (:inherit warning :underline nil))))
 '(compilation-warning-face ((((class color) (min-colors 89)) (:foreground "#b58900" :weight normal :underline nil))))
 '(compilation-mode-line-exit ((((class color) (min-colors 89)) (:inherit compilation-info :foreground "#859900" :weight bold))))
 '(compilation-mode-line-fail ((((class color) (min-colors 89)) (:inherit compilation-error :foreground "#dc322f" :weight bold))))
 '(compilation-mode-line-run ((((class color) (min-colors 89)) (:foreground "#cb4b16" :weight bold))))
 '(cua-global-mark ((((class color) (min-colors 89)) (:background "#b58900" :foreground "#002b36"))))
 '(cua-rectangle ((((class color) (min-colors 89)) (:inherit region :background "#d33682" :foreground "#002b36"))))
 '(cua-rectangle-noselect ((((class color) (min-colors 89)) (:inherit region :background "#073642" :foreground "#586e75"))))
 '(diary ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(dired-directory ((((class color) (min-colors 89)) (:foreground "#268bd2" :weight normal))))
 '(dired-flagged ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(dired-header ((((class color) (min-colors 89)) (:foreground "#002b36" :background "#268bd2"))))
 '(dired-ignored ((((class color) (min-colors 89)) (:inherit shadow))))
 '(dired-mark ((((class color) (min-colors 89)) (:foreground "#b58900" :weight bold))))
 '(dired-marked ((((class color) (min-colors 89)) (:foreground "#d33682" :weight bold))))
 '(dired-perm-write ((t (:inherit default))))
 '(dired-symlink ((((class color) (min-colors 89)) (:foreground "#2aa198" :weight normal :slant italic))))
 '(dired-warning ((((class color) (min-colors 89)) (:foreground "#cb4b16" :underline t))))
 '(dropdown-list-face ((((class color) (min-colors 89)) (:background "#073642" :foreground "#2aa198"))))
 '(dropdown-list-selection-face ((((class color) (min-colors 89)) (:background "#00736F" :foreground "#69CABF"))))
 '(ecb-default-highlight-face ((((class color) (min-colors 89)) (:background "#268bd2" :foreground "#002b36"))))
 '(ecb-history-bucket-node-dir-soure-path-face ((((class color) (min-colors 89)) (:inherit ecb-history-bucket-node-face :foreground "#b58900"))))
 '(ecb-source-in-directories-buffer-face ((((class color) (min-colors 89)) (:inherit ecb-directories-general-face :foreground "#839496"))))
 '(ecb-history-dead-buffer-face ((((class color) (min-colors 89)) (:inherit ecb-history-general-face :foreground "#586e75"))))
 '(ecb-directory-not-accessible-face ((((class color) (min-colors 89)) (:inherit ecb-directories-general-face :foreground "#586e75"))))
 '(ecb-bucket-node-face ((((class color) (min-colors 89)) (:inherit ecb-default-general-face :weight normal :foreground "#268bd2"))))
 '(ecb-tag-header-face ((((class color) (min-colors 89)) (:background "#073642"))))
 '(ecb-analyse-bucket-element-face ((((class color) (min-colors 89)) (:inherit ecb-analyse-general-face :foreground "#859900"))))
 '(ecb-directories-general-face ((((class color) (min-colors 89)) (:inherit ecb-default-general-face :height 1.0))))
 '(ecb-method-non-semantic-face ((((class color) (min-colors 89)) (:inherit ecb-methods-general-face :foreground "#2aa198"))))
 '(ecb-mode-line-prefix-face ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(ecb-tree-guide-line-face ((((class color) (min-colors 89)) (:inherit ecb-default-general-face :foreground "#073642" :height 1.0))))
 '(ee-bookmarked ((((class color) (min-colors 89)) (:foreground "#93a1a1"))))
 '(ee-category ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(ee-link ((((class color) (min-colors 89)) (:inherit link))))
 '(ee-link-visited ((((class color) (min-colors 89)) (:inherit link-visited))))
 '(ee-marked ((((class color) (min-colors 89)) (:foreground "#d33682" :weight bold))))
 '(ee-omitted ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(ee-shadow ((((class color) (min-colors 89)) (:inherit shadow))))
 '(grep-context-face ((((class color) (min-colors 89)) (:foreground "#839496"))))
 '(grep-error-face ((((class color) (min-colors 89)) (:foreground "#dc322f" :weight bold :underline t))))
 '(grep-hit-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(grep-match-face ((((class color) (min-colors 89)) (:foreground "#cb4b16" :weight bold))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "#002b36" :background "#d33682" :weight normal))))
 '(isearch-fail ((((class color) (min-colors 89)) (:foreground "#dc322f" :background "#002b36" :bold t))))
 '(Man-overstrike ((((class color) (min-colors 89)) (:foreground "#268bd2" :weight bold))))
 '(Man-reverse ((((class color) (min-colors 89)) (:foreground "#cb4b16"))))
 '(Man-underline ((((class color) (min-colors 89)) (:foreground "#859900" :underline t))))
 '(menu ((((class color) (min-colors 89)) (:foreground "#839496" :background "#002b36"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#839496"))))
 '(mode-line ((((class color) (min-colors 89)) (:inverse-video unspecified :underline unspecified :foreground "#839496" :background "#073642" :box (:line-width 1 :color "#073642" :style unspecified)))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:foreground "#93a1a1" :weight bold))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:inverse-video unspecified :underline unspecified :foreground "#586e75" :background "#002b36" :box (:line-width 1 :color "#073642" :style unspecified)))))
 '(header-line ((((class color) (min-colors 89)) (:inverse-video unspecified :underline unspecified :foreground "#93a1a1" :background "#073642" :box (:line-width 1 :color "#073642" :style unspecified)))))
 '(region ((((class color) (min-colors 89)) (:foreground "#002b36" :background "#93a1a1"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#073642"))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:background "#dc322f"))))
 '(vertical-border ((((class color) (min-colors 89)) (:foreground "#839496"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#839496" :weight bold))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#268bd2" :weight bold))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(font-lock-function-name-face ((t (:foreground "indian red"))))
 '(font-lock-keyword-face ((t (:foreground "RoyalBlue1" :weight normal))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:foreground "#b58900" :weight bold))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:foreground "#b58900" :weight bold))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:foreground "#859900" :weight bold))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(font-lock-type-face ((t (:inherit default))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:foreground "#cb4b16" :weight bold :underline t))))
 '(c-annotation-face ((((class color) (min-colors 89)) (:inherit font-lock-constant-face))))
 '(ace-jump-face-background ((((class color) (min-colors 89)) (:foreground "#586e75" :background "#002b36" :inverse-video nil))))
 '(ace-jump-face-foreground ((((class color) (min-colors 89)) (:foreground "#dc322f" :background "#002b36" :inverse-video nil :weight bold))))
 '(font-latex-bold-face ((((class color) (min-colors 89)) (:inherit bold :foreground "#93a1a1"))))
 '(font-latex-doctex-documentation-face ((((class color) (min-colors 89)) (:background unspecified))))
 '(font-latex-doctex-preprocessor-face ((((class color) (min-colors 89)) (:inherit (font-latex-doctex-documentation-face font-lock-builtin-face font-lock-preprocessor-face)))))
 '(font-latex-italic-face ((((class color) (min-colors 89)) (:inherit italic :foreground "#93a1a1"))))
 '(font-latex-math-face ((t (:foreground "LightGoldenrod1"))))
 '(font-latex-sectioning-0-face ((((class color) (min-colors 89)) (:inherit font-latex-sectioning-1-face :height 1.1))))
 '(font-latex-sectioning-1-face ((((class color) (min-colors 89)) (:inherit font-latex-sectioning-2-face :height 1.1))))
 '(font-latex-sectioning-2-face ((((class color) (min-colors 89)) (:inherit font-latex-sectioning-3-face :height 1.1))))
 '(font-latex-sectioning-3-face ((((class color) (min-colors 89)) (:inherit font-latex-sectioning-4-face :height 1.1))))
 '(font-latex-sectioning-4-face ((((class color) (min-colors 89)) (:inherit font-latex-sectioning-5-face :height 1.1))))
 '(font-latex-sectioning-5-face ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#b58900" :weight bold))))
 '(font-latex-sedate-face ((((class color) (min-colors 89)) (:foreground "#93a1a1"))))
 '(font-latex-slide-title-face ((((class color) (min-colors 89)) (:inherit (variable-pitch font-lock-type-face) :weight bold :height 1.2))))
 '(font-latex-string-face ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(font-latex-subscript-face ((((class color) (min-colors 89)) (:height 0.8))))
 '(font-latex-superscript-face ((((class color) (min-colors 89)) (:height 0.8))))
 '(font-latex-verbatim-face ((((class color) (min-colors 89)) (:inherit fixed-pitch :foreground "#839496" :slant italic))))
 '(font-latex-warning-face ((((class color) (min-colors 89)) (:inherit bold :foreground "#cb4b16"))))
 '(ac-candidate-face ((((class color) (min-colors 89)) (:background "#073642" :foreground "#2aa198"))))
 '(ac-selection-face ((((class color) (min-colors 89)) (:background "#00736F" :foreground "#69CABF"))))
 '(ac-candidate-mouse-face ((((class color) (min-colors 89)) (:background "#69CABF" :foreground "#00736F"))))
 '(ac-completion-face ((((class color) (min-colors 89)) (:foreground "#93a1a1" :underline t))))
 '(ac-gtags-candidate-face ((((class color) (min-colors 89)) (:background "#073642" :foreground "#268bd2"))))
 '(ac-gtags-selection-face ((((class color) (min-colors 89)) (:background "#00629D" :foreground "#69B7F0"))))
 '(ac-yasnippet-candidate-face ((((class color) (min-colors 89)) (:background "#073642" :foreground "#b58900"))))
 '(ac-yasnippet-selection-face ((((class color) (min-colors 89)) (:background "#7B6000" :foreground "#DEB542"))))
 '(ahs-definition-face ((((class color) (min-colors 89)) (:foreground "#d33682" :background "#002b36" :slant normal))))
 '(ahs-edit-mode-face ((((class color) (min-colors 89)) (:foreground "#002b36" :background "#d33682"))))
 '(ahs-face ((((class color) (min-colors 89)) (:foreground "#d33682" :background "#002b36"))))
 '(ahs-plugin-bod-face ((((class color) (min-colors 89)) (:foreground "#d33682" :background unspecified))))
 '(ahs-plugin-defalt-face ((((class color) (min-colors 89)) (:foreground "#d33682" :background unspecified))))
 '(ahs-plugin-whole-buffer-face ((((class color) (min-colors 89)) (:foreground "#d33682" :background unspecified))))
 '(ahs-warning-face ((((class color) (min-colors 89)) (:foreground "#dc322f" :weight bold))))
 '(android-mode-debug-face ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(android-mode-error-face ((((class color) (min-colors 89)) (:foreground "#cb4b16" :weight bold))))
 '(android-mode-info-face ((((class color) (min-colors 89)) (:foreground "#839496"))))
 '(android-mode-verbose-face ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(android-mode-warning-face ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(bm-face ((((class color) (min-colors 89)) (:background "#7B6000" :foreground "#002b36"))))
 '(bm-fringe-face ((((class color) (min-colors 89)) (:background "#7B6000" :foreground "#002b36"))))
 '(bm-fringe-persistent-face ((((class color) (min-colors 89)) (:background "#546E00" :foreground "#002b36"))))
 '(bm-persistent-face ((((class color) (min-colors 89)) (:background "#546E00" :foreground "#002b36"))))
 '(cfw:face-day-title ((((class color) (min-colors 89)) (:background "#073642"))))
 '(cfw:face-annotation ((((class color) (min-colors 89)) (:inherit cfw:face-day-title :foreground "#b58900"))))
 '(cfw:face-default-content ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(cfw:face-default-day ((((class color) (min-colors 89)) (:inherit cfw:face-day-title :weight bold))))
 '(cfw:face-disable ((((class color) (min-colors 89)) (:inherit cfw:face-day-title :foreground "#586e75"))))
 '(cfw:face-grid ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(cfw:face-header ((((class color) (min-colors 89)) (:foreground "#69B7F0" :background "#00629D" :weight bold))))
 '(cfw:face-holiday ((((class color) (min-colors 89)) (:background nil :foreground "#dc322f" :weight bold))))
 '(cfw:face-periods ((((class color) (min-colors 89)) (:foreground "#d33682"))))
 '(cfw:face-select ((((class color) (min-colors 89)) (:background "#93115C" :foreground "#F771AC"))))
 '(cfw:face-saturday ((((class color) (min-colors 89)) (:foreground "#69CABF" :background "#00736F"))))
 '(cfw:face-sunday ((((class color) (min-colors 89)) (:foreground "#FF6E64" :background "#990A1B" :weight bold))))
 '(cfw:face-title ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#b58900" :weight bold :height 2.0))))
 '(cfw:face-today ((((class color) (min-colors 89)) (:weight bold :background "#073642" :foreground nil))))
 '(cfw:face-today-title ((((class color) (min-colors 89)) (:background "#7B6000" :foreground "#DEB542" :weight bold))))
 '(cfw:face-toolbar ((((class color) (min-colors 89)) (:background "#073642" :foreground "#839496"))))
 '(cfw:face-toolbar-button-off ((((class color) (min-colors 89)) (:background "#7B6000" :foreground "#DEB542" :weight bold))))
 '(cfw:face-toolbar-button-on ((((class color) (min-colors 89)) (:background "#DEB542" :foreground "#7B6000" :weight bold))))
 '(clojure-test-failure-face ((t (:foreground "#cb4b16" :weight bold :underline t))))
 '(clojure-test-error-face ((t (:foreground "#dc322f" :weight bold :underline t))))
 '(clojure-test-success-face ((t (:foreground "#859900" :weight bold :underline t))))
 '(cscope-file-face ((((class color) (min-colors 89)) (:foreground "#859900" :weight bold))))
 '(cscope-function-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(cscope-line-number-face ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(cscope-line-face ((((class color) (min-colors 89)) (:foreground "#839496"))))
 '(cscope-mouse-face ((((class color) (min-colors 89)) (:background "#268bd2" :foreground "#839496"))))
 '(ctbl:face-cell-select ((((class color) (min-colors 89)) (:background "#073642" :foreground "#93a1a1" :underline "#93a1a1" :weight bold))))
 '(ctbl:face-continue-bar ((((class color) (min-colors 89)) (:background "#073642" :foreground "#b58900"))))
 '(ctbl:face-row-select ((((class color) (min-colors 89)) (:background "#073642" :foreground "#839496" :underline t))))
 '(coffee-mode-class-name ((((class color) (min-colors 89)) (:foreground "#b58900" :weight bold))))
 '(coffee-mode-function-param ((((class color) (min-colors 89)) (:foreground "#6c71c4" :slant italic))))
 '(custom-variable-tag ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(custom-comment-tag ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(custom-group-tag ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(custom-state ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(diff-added ((((class color) (min-colors 89)) (:foreground "#859900" :background "#002b36"))))
 '(diff-changed ((((class color) (min-colors 89)) (:foreground "#268bd2" :background "#002b36"))))
 '(diff-removed ((((class color) (min-colors 89)) (:foreground "#dc322f" :background "#002b36"))))
 '(diff-header ((((class color) (min-colors 89)) (:background "#002b36"))))
 '(diff-file-header ((((class color) (min-colors 89)) (:background "#002b36" :foreground "#839496" :weight bold))))
 '(diff-refine-added ((((class color) (min-colors 89)) :foreground "#002b36" :background "#859900")))
 '(diff-refine-change ((((class color) (min-colors 89)) :foreground "#002b36" :background "#268bd2")))
 '(diff-refine-removed ((((class color) (min-colors 89)) (:foreground "#002b36" :background "#dc322f"))))
 '(ediff-fine-diff-A ((((class color) (min-colors 89)) (:background "#8B2C02"))))
 '(ediff-fine-diff-B ((((class color) (min-colors 89)) (:background "#546E00"))))
 '(ediff-fine-diff-C ((((class color) (min-colors 89)) (:background "#7B6000"))))
 '(ediff-current-diff-C ((((class color) (min-colors 89)) (:background "#00629D"))))
 '(ediff-even-diff-A ((((class color) (min-colors 89)) (:background "#586e75" :foreground "#fdf6e3"))))
 '(ediff-odd-diff-A ((((class color) (min-colors 89)) (:background "#586e75" :foreground "#002b36"))))
 '(ediff-even-diff-B ((((class color) (min-colors 89)) (:background "#586e75" :foreground "#002b36"))))
 '(ediff-odd-diff-B ((((class color) (min-colors 89)) (:background "#586e75" :foreground "#fdf6e3"))))
 '(ediff-even-diff-C ((((class color) (min-colors 89)) (:background "#586e75" :foreground "#839496"))))
 '(ediff-odd-diff-C ((((class color) (min-colors 89)) (:background "#586e75" :foreground "#002b36"))))
 '(epc:face-title ((((class color) (min-colors 89)) (:foreground "#268bd2" :background "#002b36" :weight normal :underline nil))))
 '(eshell-prompt ((((class color) (min-colors 89)) (:foreground "#b58900" :weight bold))))
 '(fic-author-face ((((class color) (min-colors 89)) (:background "#002b36" :foreground "#cb4b16" :underline t :slant italic))))
 '(fic-face ((((class color) (min-colors 89)) (:background "#002b36" :foreground "#cb4b16" :weight normal :slant italic))))
 '(flx-highlight-face ((((class color) (min-colors 89)) (:foreground "#268bd2" :weight normal :underline nil))))
 '(flymake-errline ((((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#dc322f") :inherit unspecified :foreground unspecified :background unspecified)) (((class color) (min-colors 89)) (:foreground "#FF6E64" :background "#990A1B" :weight bold :underline t))))
 '(flymake-infoline ((((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#859900") :inherit unspecified :foreground unspecified :background unspecified)) (((class color) (min-colors 89)) (:foreground "#B4C342" :background "#546E00"))))
 '(flymake-warnline ((((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#b58900") :inherit unspecified :foreground unspecified :background unspecified)) (((class color) (min-colors 89)) (:foreground "#DEB542" :background "#7B6000" :weight bold :underline t))))
 '(flycheck-error ((((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#dc322f") :inherit unspecified)) (((class color) (min-colors 89)) (:foreground "#FF6E64" :background "#990A1B" :weight bold :underline t))))
 '(flycheck-warning ((((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#b58900") :inherit unspecified)) (((class color) (min-colors 89)) (:foreground "#DEB542" :background "#7B6000" :weight bold :underline t))))
 '(flycheck-fringe-error ((((class color) (min-colors 89)) (:foreground "#FF6E64" :background "#990A1B" :weight bold))))
 '(flycheck-fringe-warning ((((class color) (min-colors 89)) (:foreground "#DEB542" :background "#7B6000" :weight bold))))
 '(flyspell-duplicate ((((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#b58900") :inherit unspecified)) (((class color) (min-colors 89)) (:foreground "#b58900" :weight bold :underline t))))
 '(flyspell-incorrect ((((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#dc322f") :inherit unspecified)) (((class color) (min-colors 89)) (:foreground "#dc322f" :weight bold :underline t))))
 '(erc-action-face ((((class color) (min-colors 89)) (:inherit erc-default-face))))
 '(erc-bold-face ((((class color) (min-colors 89)) (:weight bold))))
 '(erc-current-nick-face ((((class color) (min-colors 89)) (:foreground "#268bd2" :weight bold))))
 '(erc-dangerous-host-face ((((class color) (min-colors 89)) (:inherit font-lock-warning-face))))
 '(erc-default-face ((((class color) (min-colors 89)) (:foreground "#839496"))))
 '(erc-highlight-face ((((class color) (min-colors 89)) (:inherit erc-default-face :background "#073642"))))
 '(erc-direct-msg-face ((((class color) (min-colors 89)) (:inherit erc-default-face))))
 '(erc-error-face ((((class color) (min-colors 89)) (:inherit font-lock-warning-face))))
 '(erc-fool-face ((((class color) (min-colors 89)) (:inherit erc-default-face))))
 '(erc-input-face ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(erc-keyword-face ((((class color) (min-colors 89)) (:foreground "#268bd2" :weight bold))))
 '(erc-nick-default-face ((((class color) (min-colors 89)) (:foreground "#b58900" :weight bold))))
 '(erc-my-nick-face ((((class color) (min-colors 89)) (:foreground "#dc322f" :weight bold))))
 '(erc-nick-msg-face ((((class color) (min-colors 89)) (:inherit erc-default-face))))
 '(erc-notice-face ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(erc-pal-face ((((class color) (min-colors 89)) (:foreground "#cb4b16" :weight bold))))
 '(erc-prompt-face ((((class color) (min-colors 89)) (:foreground "#cb4b16" :background "#002b36" :weight bold))))
 '(erc-timestamp-face ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(erc-underline-face ((t (:underline t))))
 '(git-gutter:added ((((class color) (min-colors 89)) (:background "#859900" :foreground "#002b36" :weight bold))))
 '(git-gutter:deleted ((((class color) (min-colors 89)) (:background "#dc322f" :foreground "#002b36" :weight bold))))
 '(git-gutter:modified ((((class color) (min-colors 89)) (:background "#268bd2" :foreground "#002b36" :weight bold))))
 '(git-gutter:unchanged ((((class color) (min-colors 89)) (:background "#073642" :foreground "#002b36" :weight bold))))
 '(git-gutter-fr:added ((((class color) (min-colors 89)) (:foreground "#859900" :weight bold))))
 '(git-gutter-fr:deleted ((((class color) (min-colors 89)) (:foreground "#dc322f" :weight bold))))
 '(git-gutter-fr:modified ((((class color) (min-colors 89)) (:foreground "#268bd2" :weight bold))))
 '(guide-key/highlight-command-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(guide-key/key-face ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(guide-key/prefix-command-face ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(gnus-group-mail-1 ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-mail-1-empty))))
 '(gnus-group-mail-1-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-1-empty))))
 '(gnus-group-mail-2 ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-mail-2-empty))))
 '(gnus-group-mail-2-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-2-empty))))
 '(gnus-group-mail-3 ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-mail-3-empty))))
 '(gnus-group-mail-3-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-3-empty))))
 '(gnus-group-mail-low ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-mail-low-empty))))
 '(gnus-group-mail-low-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-low-empty))))
 '(gnus-group-news-1 ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-news-1-empty))))
 '(gnus-group-news-2 ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-news-2-empty))))
 '(gnus-group-news-3 ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-news-3-empty))))
 '(gnus-group-news-4 ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-news-4-empty))))
 '(gnus-group-news-5 ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-news-5-empty))))
 '(gnus-group-news-6 ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-news-6-empty))))
 '(gnus-group-news-low ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-news-low-empty))))
 '(gnus-header-content ((((class color) (min-colors 89)) (:inherit message-header-other))))
 '(gnus-header-from ((((class color) (min-colors 89)) (:inherit message-header-other))))
 '(gnus-header-name ((((class color) (min-colors 89)) (:inherit message-header-name))))
 '(gnus-header-newsgroups ((((class color) (min-colors 89)) (:inherit message-header-other))))
 '(gnus-header-subject ((((class color) (min-colors 89)) (:inherit message-header-subject))))
 '(gnus-summary-cancelled ((((class color) (min-colors 89)) (:foreground "#cb4b16"))))
 '(gnus-summary-high-ancient ((((class color) (min-colors 89)) (:foreground "#268bd2" :weight bold))))
 '(gnus-summary-high-read ((((class color) (min-colors 89)) (:foreground "#859900" :weight bold))))
 '(gnus-summary-high-ticked ((((class color) (min-colors 89)) (:foreground "#cb4b16" :weight bold))))
 '(gnus-summary-high-unread ((((class color) (min-colors 89)) (:foreground "#839496" :weight bold))))
 '(gnus-summary-low-ancient ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(gnus-summary-low-read ((t (:foreground "#859900"))))
 '(gnus-summary-low-ticked ((((class color) (min-colors 89)) (:foreground "#cb4b16"))))
 '(gnus-summary-low-unread ((((class color) (min-colors 89)) (:foreground "#839496"))))
 '(gnus-summary-normal-ancient ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(gnus-summary-normal-read ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(gnus-summary-normal-ticked ((((class color) (min-colors 89)) (:foreground "#cb4b16"))))
 '(gnus-summary-normal-unread ((((class color) (min-colors 89)) (:foreground "#839496"))))
 '(gnus-summary-selected ((((class color) (min-colors 89)) (:foreground "#b58900" :weight bold))))
 '(gnus-cite-1 ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(gnus-cite-2 ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(gnus-cite-3 ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(gnus-cite-4 ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(gnus-cite-5 ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(gnus-cite-6 ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(gnus-cite-7 ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(gnus-cite-8 ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(gnus-cite-9 ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(gnus-cite-10 ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(gnus-cite-11 ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(gnus-group-news-1-empty ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(gnus-group-news-2-empty ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(gnus-group-news-3-empty ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(gnus-group-news-4-empty ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(gnus-group-news-5-empty ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(gnus-group-news-6-empty ((((class color) (min-colors 89)) (:foreground "#00629D"))))
 '(gnus-group-news-low-empty ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(gnus-signature ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(gnus-x-face ((((class color) (min-colors 89)) (:background "#839496" :foreground "#002b36"))))
 '(helm-apt-deinstalled ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(helm-apt-installed ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(helm-bookmark-directory ((((class color) (min-colors 89)) (:inherit helm-ff-directory))))
 '(helm-bookmark-file ((((class color) (min-colors 89)) (:foreground "#839496"))))
 '(helm-bookmark-gnus ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(helm-bookmark-info ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(helm-bookmark-man ((((class color) (min-colors 89)) (:foreground "#6c71c4"))))
 '(helm-bookmark-w3m ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(helm-bookmarks-su ((((class color) (min-colors 89)) (:foreground "#cb4b16"))))
 '(helm-buffer-not-saved ((((class color) (min-colors 89)) (:foreground "#cb4b16"))))
 '(helm-buffer-saved-out ((((class color) (min-colors 89)) (:foreground "#dc322f" :background "#002b36" :inverse-video t))))
 '(helm-buffer-size ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(helm-candidate-number ((((class color) (min-colors 89)) (:background "#073642" :foreground "#93a1a1" :bold t))))
 '(helm-ff-directory ((((class color) (min-colors 89)) (:background "#002b36" :foreground "#268bd2"))))
 '(helm-ff-executable ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(helm-ff-file ((((class color) (min-colors 89)) (:background "#002b36" :foreground "#839496"))))
 '(helm-ff-invalid-symlink ((((class color) (min-colors 89)) (:background "#002b36" :foreground "#cb4b16" :slant italic))))
 '(helm-ff-prefix ((((class color) (min-colors 89)) (:background "#b58900" :foreground "#002b36"))))
 '(helm-ff-symlink ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(helm-grep-file ((((class color) (min-colors 89)) (:foreground "#2aa198" :underline t))))
 '(helm-grep-finish ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(helm-grep-lineno ((((class color) (min-colors 89)) (:foreground "#cb4b16"))))
 '(helm-grep-match ((((class color) (min-colors 89)) (:inherit match))))
 '(helm-grep-running ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(helm-header ((((class color) (min-colors 89)) (:inherit header-line))))
 '(helm-lisp-completion-info ((((class color) (min-colors 89)) (:foreground "#839496"))))
 '(helm-lisp-show-completion ((((class color) (min-colors 89)) (:foreground "#b58900" :background "#073642" :bold t))))
 '(helm-M-x-key ((((class color) (min-colors 89)) (:foreground "#cb4b16" :underline t))))
 '(helm-moccur-buffer ((((class color) (min-colors 89)) (:foreground "#2aa198" :underline t))))
 '(helm-match ((((class color) (min-colors 89)) (:inherit match))))
 '(helm-selection ((((class color) (min-colors 89)) (:background "#073642" :underline t))))
 '(helm-selection-line ((((class color) (min-colors 89)) (:background "#073642" :foreground "#93a1a1" :underline nil))))
 '(helm-separator ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(helm-source-header ((((class color) (min-colors 89)) (:background "#00629D" :foreground "#002b36" :underline nil))))
 '(helm-time-zone-current ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(helm-time-zone-home ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(helm-visible-mark ((((class color) (min-colors 89)) (:background "#002b36" :foreground "#d33682" :bold t))))
 '(hi-yellow ((((class color) (min-colors 89)) (:foreground "#7B6000" :background "#DEB542"))))
 '(hi-pink ((((class color) (min-colors 89)) (:foreground "#93115C" :background "#F771AC"))))
 '(hi-green ((((class color) (min-colors 89)) (:foreground "#546E00" :background "#B4C342"))))
 '(hi-blue ((((class color) (min-colors 89)) (:foreground "#00629D" :background "#69B7F0"))))
 '(hi-black-b ((((class color) (min-colors 89)) (:foreground "#93a1a1" :background "#002b36" :weight bold))))
 '(hi-blue-b ((((class color) (min-colors 89)) (:foreground "#00629D" :weight bold))))
 '(hi-green-b ((((class color) (min-colors 89)) (:foreground "#546E00" :weight bold))))
 '(hi-red-b ((((class color) (min-colors 89)) (:foreground "#dc322f" :weight bold))))
 '(hi-black-hb ((((class color) (min-colors 89)) (:foreground "#93a1a1" :background "#002b36" :weight bold))))
 '(highlight-changes ((((class color) (min-colors 89)) (:foreground "#cb4b16"))))
 '(highlight-changes-delete ((((class color) (min-colors 89)) (:foreground "#dc322f" :underline t))))
 '(highlight-indentation-face ((((class color) (min-colors 89)) (:background "#073642"))))
 '(highlight-indentation-current-column-face ((((class color) (min-colors 89)) (:background "#073642"))))
 '(hl-line ((((class color) (min-colors 89)) (:background "#073642"))))
 '(hl-line-face ((((class color) (min-colors 89)) (:background "#073642"))))
 '(ido-first-match ((((class color) (min-colors 89)) (:foreground "#b58900" :weight normal))))
 '(ido-only-match ((((class color) (min-colors 89)) (:foreground "#002b36" :background "#b58900" :weight normal))))
 '(ido-subdir ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(ido-incomplete-regexp ((((class color) (min-colors 89)) (:foreground "#dc322f" :weight bold))))
 '(ido-indicator ((((class color) (min-colors 89)) (:background "#dc322f" :foreground "#002b36" :width condensed))))
 '(ido-virtual ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(jabber-activity-face ((((class color) (min-colors 89)) (:weight bold :foreground "#dc322f"))))
 '(jabber-activity-personal-face ((((class color) (min-colors 89)) (:weight bold :foreground "#268bd2"))))
 '(jabber-chat-error ((((class color) (min-colors 89)) (:weight bold :foreground "#dc322f"))))
 '(jabber-chat-prompt-foreign ((((class color) (min-colors 89)) (:weight bold :foreground "#dc322f"))))
 '(jabber-chat-prompt-local ((((class color) (min-colors 89)) (:weight bold :foreground "#268bd2"))))
 '(jabber-chat-prompt-system ((((class color) (min-colors 89)) (:weight bold :foreground "#859900"))))
 '(jabber-chat-text-foreign ((((class color) (min-colors 89)) (:foreground "#93a1a1"))))
 '(jabber-chat-text-local ((((class color) (min-colors 89)) (:foreground "#839496"))))
 '(jabber-chat-rare-time-face ((((class color) (min-colors 89)) (:underline t :foreground "#859900"))))
 '(jabber-roster-user-away ((((class color) (min-colors 89)) (:slant italic :foreground "#859900"))))
 '(jabber-roster-user-chatty ((((class color) (min-colors 89)) (:weight bold :foreground "#cb4b16"))))
 '(jabber-roster-user-dnd ((((class color) (min-colors 89)) (:slant italic :foreground "#dc322f"))))
 '(jabber-roster-user-error ((((class color) (min-colors 89)) (:weight light :slant italic :foreground "#dc322f"))))
 '(jabber-roster-user-offline ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(jabber-roster-user-online ((((class color) (min-colors 89)) (:weight bold :foreground "#268bd2"))))
 '(jabber-roster-user-xa ((((class color) (min-colors 89)) (:slant italic :foreground "#d33682"))))
 '(js2-error ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(js2-external-variable ((((class color) (min-colors 89)) (:foreground "#cb4b16"))))
 '(js2-function-param ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(js2-instance-member ((((class color) (min-colors 89)) (:foreground "#d33682"))))
 '(js2-jsdoc-html-tag-delimiter ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(js2-jsdoc-html-tag-name ((((class color) (min-colors 89)) (:foreground "#cb4b16"))))
 '(js2-jsdoc-tag ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(js2-jsdoc-type ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(js2-jsdoc-value ((((class color) (min-colors 89)) (:foreground "#6c71c4"))))
 '(js2-magic-paren ((((class color) (min-colors 89)) (:underline t))))
 '(js2-private-function-call ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(js2-private-member ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(js2-warning ((((class color) (min-colors 89)) (:underline "#cb4b16"))))
 '(jedi:highlight-function-argument ((((class color) (min-colors 89)) (:inherit bold))))
 '(linum ((((class color) (min-colors 89)) (:foreground "#586e75" :background "#002b36"))))
 '(lusty-directory-face ((((class color) (min-colors 89)) (:inherit dired-directory))))
 '(lusty-file-face ((((class color) (min-colors 89)) nil)))
 '(lusty-match-face ((((class color) (min-colors 89)) (:inherit ido-first-match))))
 '(lusty-slash-face ((((class color) (min-colors 89)) (:foreground "#2aa198" :weight bold))))
 '(magit-section-title ((((class color) (min-colors 89)) (:foreground "#b58900" :weight bold))))
 '(magit-branch ((((class color) (min-colors 89)) (:foreground "#cb4b16" :weight bold))))
 '(magit-item-highlight ((((class color) (min-colors 89)) (:background "#073642" :weight unspecified))))
 '(magit-log-author ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(magit-log-graph ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(magit-log-head-label-bisect-bad ((((class color) (min-colors 89)) (:background "#FF6E64" :foreground "#990A1B" :box 1))))
 '(magit-log-head-label-bisect-good ((((class color) (min-colors 89)) (:background "#B4C342" :foreground "#546E00" :box 1))))
 '(magit-log-head-label-default ((((class color) (min-colors 89)) (:background "#073642" :box 1))))
 '(magit-log-head-label-local ((((class color) (min-colors 89)) (:background "#00629D" :foreground "#69B7F0" :box 1))))
 '(magit-log-head-label-patches ((((class color) (min-colors 89)) (:background "#990A1B" :foreground "#FF6E64" :box 1))))
 '(magit-log-head-label-remote ((((class color) (min-colors 89)) (:background "#546E00" :foreground "#B4C342" :box 1))))
 '(magit-log-head-label-tags ((((class color) (min-colors 89)) (:background "#7B6000" :foreground "#DEB542" :box 1))))
 '(magit-log-sha1 ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(message-cited-text ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(message-header-name ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(message-header-other ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(message-header-to ((((class color) (min-colors 89)) (:foreground "#b58900" :weight bold))))
 '(message-header-cc ((((class color) (min-colors 89)) (:foreground "#cb4b16" :weight bold))))
 '(message-header-newsgroups ((((class color) (min-colors 89)) (:foreground "#b58900" :weight bold))))
 '(message-header-subject ((((class color) (min-colors 89)) (:foreground "#cb4b16"))))
 '(message-header-xheader ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(message-mml ((((class color) (min-colors 89)) (:foreground "#b58900" :weight bold))))
 '(message-separator ((((class color) (min-colors 89)) (:foreground "#586e75" :slant italic))))
 '(mew-face-header-subject ((((class color) (min-colors 89)) (:foreground "#cb4b16"))))
 '(mew-face-header-from ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(mew-face-header-date ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(mew-face-header-to ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(mew-face-header-key ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(mew-face-header-private ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(mew-face-header-important ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(mew-face-header-marginal ((((class color) (min-colors 89)) (:foreground "#839496" :weight bold))))
 '(mew-face-header-warning ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(mew-face-header-xmew ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(mew-face-header-xmew-bad ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(mew-face-body-url ((((class color) (min-colors 89)) (:foreground "#cb4b16"))))
 '(mew-face-body-comment ((((class color) (min-colors 89)) (:foreground "#839496" :slant italic))))
 '(mew-face-body-cite1 ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(mew-face-body-cite2 ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(mew-face-body-cite3 ((((class color) (min-colors 89)) (:foreground "#cb4b16"))))
 '(mew-face-body-cite4 ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(mew-face-body-cite5 ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(mew-face-mark-review ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(mew-face-mark-escape ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(mew-face-mark-delete ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(mew-face-mark-unlink ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(mew-face-mark-refile ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(mew-face-mark-unread ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(mew-face-eof-message ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(mew-face-eof-part ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(mingus-directory-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(mingus-pausing-face ((((class color) (min-colors 89)) (:foreground "#d33682"))))
 '(mingus-playing-face ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(mingus-playlist-face ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(mingus-song-file-face ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(mingus-stopped-face ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(moccur-current-line-face ((((class color) (min-colors 89)) (:underline t))))
 '(moccur-edit-done-face ((((class color) (min-colors 89)) (:foreground "#586e75" :background "#002b36" :slant italic))))
 '(moccur-edit-face ((((class color) (min-colors 89)) (:background "#b58900" :foreground "#002b36"))))
 '(moccur-edit-file-face ((((class color) (min-colors 89)) (:background "#073642"))))
 '(moccur-edit-reject-face ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(moccur-face ((((class color) (min-colors 89)) (:background "#073642" :foreground "#93a1a1" :weight bold))))
 '(search-buffers-face ((((class color) (min-colors 89)) (:background "#073642" :foreground "#93a1a1" :weight bold))))
 '(search-buffers-header-face ((((class color) (min-colors 89)) (:background "#073642" :foreground "#b58900" :weight bold))))
 '(mu4e-cited-1-face ((((class color) (min-colors 89)) (:foreground "#859900" :slant italic :weight normal))))
 '(mu4e-cited-2-face ((((class color) (min-colors 89)) (:foreground "#268bd2" :slant italic :weight normal))))
 '(mu4e-cited-3-face ((((class color) (min-colors 89)) (:foreground "#cb4b16" :slant italic :weight normal))))
 '(mu4e-cited-4-face ((((class color) (min-colors 89)) (:foreground "#b58900" :slant italic :weight normal))))
 '(mu4e-cited-5-face ((((class color) (min-colors 89)) (:foreground "#2aa198" :slant italic :weight normal))))
 '(mu4e-cited-6-face ((((class color) (min-colors 89)) (:foreground "#859900" :slant italic :weight normal))))
 '(mu4e-cited-7-face ((((class color) (min-colors 89)) (:foreground "#268bd2" :slant italic :weight normal))))
 '(mu4e-flagged-face ((((class color) (min-colors 89)) (:foreground "#d33682" :weight bold))))
 '(mu4e-view-url-number-face ((((class color) (min-colors 89)) (:foreground "#cb4b16" :weight bold))))
 '(mu4e-warning-face ((((class color) (min-colors 89)) (:foreground "#dc322f" :slant normal :weight bold))))
 '(mu4e-header-highlight-face ((((class color) (min-colors 89)) (:inherit unspecified :foreground unspecified :background "#073642" :underline "#93a1a1" :weight normal))))
 '(mumamo-background-chunk-submode1 ((((class color) (min-colors 89)) (:background "#073642"))))
 '(nav-face-heading ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(nav-face-button-num ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(nav-face-dir ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(nav-face-hdir ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(nav-face-file ((((class color) (min-colors 89)) (:foreground "#839496"))))
 '(nav-face-hfile ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(nav-flash-face ((((class color) (min-colors 89)) (:background "#073642"))))
 '(org-agenda-structure ((((class color) (min-colors 89)) (:foreground "#93a1a1" :background "#073642" :weight bold :slant normal :inverse-video nil :height 1.1 :underline nil :box (:line-width 2 :color "#002b36")))))
 '(org-agenda-calendar-event ((((class color) (min-colors 89)) (:foreground "#93a1a1"))))
 '(org-agenda-calendar-sexp ((((class color) (min-colors 89)) (:foreground "#6c71c4"))))
 '(org-agenda-date ((((class color) (min-colors 89)) (:foreground "#586e75" :background "#002b36" :weight normal :inverse-video nil :overline nil :slant normal :height 1.0 :box (:line-width 2 :color "#002b36")))))
 '(org-agenda-date-weekend ((((class color) (min-colors 89)) (:inherit org-agenda-date :inverse-video nil :background unspecified :foreground "#586e75" :weight unspecified :underline t :overline nil :box unspecified))))
 '(org-agenda-date-today ((((class color) (min-colors 89)) (:inherit org-agenda-date :inverse-video t :weight bold :underline unspecified :overline nil :box unspecified :foreground "#268bd2" :background "#002b36"))))
 '(org-agenda-done ((((class color) (min-colors 89)) (:foreground "#586e75" :slant italic))))
 '(org-archived ((((class color) (min-colors 89)) (:foreground "#586e75" :weight normal))))
 '(org-block ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(org-block-begin-line ((((class color) (min-colors 89)) (:foreground "#586e75" :slant italic))))
 '(org-checkbox ((((class color) (min-colors 89)) (:background "#002b36" :foreground "#839496" :box (:line-width 1 :style released-button)))))
 '(org-code ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(org-date ((((class color) (min-colors 89)) (:foreground "#268bd2" :underline t))))
 '(org-done ((((class color) (min-colors 89)) (:weight bold :foreground "#859900"))))
 '(org-ellipsis ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(org-formula ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(org-headline-done ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(org-hide ((((class color) (min-colors 89)) (:foreground "#002b36"))))
 '(org-level-1 ((((class color) (min-colors 89)) (:foreground "#cb4b16"))))
 '(org-level-2 ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(org-level-3 ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(org-level-4 ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(org-level-5 ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(org-level-6 ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(org-level-7 ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(org-level-8 ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(org-link ((((class color) (min-colors 89)) (:foreground "#b58900" :underline t))))
 '(org-sexp-date ((((class color) (min-colors 89)) (:foreground "#6c71c4"))))
 '(org-scheduled ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(org-scheduled-previously ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(org-scheduled-today ((((class color) (min-colors 89)) (:foreground "#268bd2" :weight normal))))
 '(org-special-keyword ((((class color) (min-colors 89)) (:foreground "#586e75" :weight bold))))
 '(org-table ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(org-tag ((((class color) (min-colors 89)) (:weight bold))))
 '(org-time-grid ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(org-todo ((((class color) (min-colors 89)) (:foreground "#dc322f" :weight bold))))
 '(org-upcoming-deadline ((((class color) (min-colors 89)) (:foreground "#b58900" :weight normal :underline nil))))
 '(org-warning ((((class color) (min-colors 89)) (:foreground "#cb4b16" :weight normal :underline nil))))
 '(org-habit-clear-face ((((class color) (min-colors 89)) (:background "#00629D" :foreground "#69B7F0"))))
 '(org-habit-clear-future-face ((((class color) (min-colors 89)) (:background "#00629D"))))
 '(org-habit-ready-face ((((class color) (min-colors 89)) (:background "#546E00" :foreground "#859900"))))
 '(org-habit-ready-future-face ((((class color) (min-colors 89)) (:background "#546E00"))))
 '(org-habit-alert-face ((((class color) (min-colors 89)) (:background "#b58900" :foreground "#7B6000"))))
 '(org-habit-alert-future-face ((((class color) (min-colors 89)) (:background "#7B6000"))))
 '(org-habit-overdue-face ((((class color) (min-colors 89)) (:background "#dc322f" :foreground "#990A1B"))))
 '(org-habit-overdue-future-face ((((class color) (min-colors 89)) (:background "#990A1B"))))
 '(org-agenda-dimmed-todo-face ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(org-agenda-restriction-lock ((((class color) (min-colors 89)) (:background "#b58900"))))
 '(org-clock-overlay ((((class color) (min-colors 89)) (:background "#b58900"))))
 '(org-column ((((class color) (min-colors 89)) (:background "#073642" :strike-through nil :underline nil :slant normal :weight normal))))
 '(org-column-title ((((class color) (min-colors 89)) (:background "#073642" :underline t :weight bold))))
 '(org-date-selected ((((class color) (min-colors 89)) (:foreground "#dc322f" :inverse-video t))))
 '(org-document-info ((((class color) (min-colors 89)) (:foreground "#839496"))))
 '(org-document-title ((((class color) (min-colors 89)) (:foreground "#93a1a1" :weight bold :height 1.44))))
 '(org-drawer ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(org-footnote ((((class color) (min-colors 89)) (:foreground "#d33682" :underline t))))
 '(org-latex-and-export-specials ((((class color) (min-colors 89)) (:foreground "#cb4b16"))))
 '(org-mode-line-clock-overrun ((((class color) (min-colors 89)) (:inherit mode-line :background "#dc322f"))))
 '(outline-1 ((((class color) (min-colors 89)) (:inherit org-level-1))))
 '(outline-2 ((((class color) (min-colors 89)) (:inherit org-level-2))))
 '(outline-3 ((((class color) (min-colors 89)) (:inherit org-level-3))))
 '(outline-4 ((((class color) (min-colors 89)) (:inherit org-level-4))))
 '(outline-5 ((((class color) (min-colors 89)) (:inherit org-level-5))))
 '(outline-6 ((((class color) (min-colors 89)) (:inherit org-level-6))))
 '(outline-7 ((((class color) (min-colors 89)) (:inherit org-level-7))))
 '(outline-8 ((((class color) (min-colors 89)) (:inherit org-level-8))))
 '(pretty-mode-symbol-face ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(popup-face ((((class color) (min-colors 89)) (:background "#073642" :foreground "#839496"))))
 '(popup-isearch-match ((((class color) (min-colors 89)) (:background "#b58900" :foreground "#002b36"))))
 '(popup-menu-face ((((class color) (min-colors 89)) (:background "#073642" :foreground "#839496"))))
 '(popup-menu-mouse-face ((((class color) (min-colors 89)) (:background "#268bd2" :foreground "#839496"))))
 '(popup-menu-selection-face ((((class color) (min-colors 89)) (:background "#d33682" :foreground "#002b36"))))
 '(popup-scroll-bar-background-face ((((class color) (min-colors 89)) (:background "#586e75"))))
 '(popup-scroll-bar-foreground-face ((((class color) (min-colors 89)) (:background "#93a1a1"))))
 '(popup-tip-face ((((class color) (min-colors 89)) (:background "#073642" :foreground "#839496"))))
 '(rainbow-delimiters-depth-1-face ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(rainbow-delimiters-depth-2-face ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(rainbow-delimiters-depth-3-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(rainbow-delimiters-depth-4-face ((((class color) (min-colors 89)) (:foreground "#cb4b16"))))
 '(rainbow-delimiters-depth-5-face ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(rainbow-delimiters-depth-6-face ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(rainbow-delimiters-depth-7-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(rainbow-delimiters-depth-8-face ((((class color) (min-colors 89)) (:foreground "#cb4b16"))))
 '(rainbow-delimiters-depth-9-face ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(rainbow-delimiters-depth-10-face ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(rainbow-delimiters-depth-11-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(rainbow-delimiters-depth-12-face ((((class color) (min-colors 89)) (:foreground "#cb4b16"))))
 '(rainbow-delimiters-unmatched-face ((((class color) (min-colors 89)) (:foreground "#839496" :background "#002b36" :inverse-video t))))
 '(rst-level-1-face ((((class color) (min-colors 89)) (:background "#b58900" :foreground "#002b36"))))
 '(rst-level-2-face ((((class color) (min-colors 89)) (:background "#2aa198" :foreground "#002b36"))))
 '(rst-level-3-face ((((class color) (min-colors 89)) (:background "#268bd2" :foreground "#002b36"))))
 '(rst-level-4-face ((((class color) (min-colors 89)) (:background "#6c71c4" :foreground "#002b36"))))
 '(rst-level-5-face ((((class color) (min-colors 89)) (:background "#d33682" :foreground "#002b36"))))
 '(rst-level-6-face ((((class color) (min-colors 89)) (:background "#dc322f" :foreground "#002b36"))))
 '(rpm-spec-dir-face ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(rpm-spec-doc-face ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(rpm-spec-ghost-face ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(rpm-spec-macro-face ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(rpm-spec-obsolete-tag-face ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(rpm-spec-package-face ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(rpm-spec-section-face ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(rpm-spec-tag-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(rpm-spec-var-face ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(sh-quoted-exec ((((class color) (min-colors 89)) (:foreground "#6c71c4" :weight bold))))
 '(sh-escaped-newline ((((class color) (min-colors 89)) (:foreground "#b58900" :weight bold))))
 '(sh-heredoc ((((class color) (min-colors 89)) (:foreground "#b58900" :weight bold))))
 '(sp-pair-overlay-face ((((class color) (min-colors 89)) (:background "#073642"))))
 '(sp-wrap-overlay-face ((((class color) (min-colors 89)) (:background "#073642"))))
 '(sp-wrap-tag-overlay-face ((((class color) (min-colors 89)) (:background "#073642"))))
 '(sp-show-pair-enclosing ((((class color) (min-colors 89)) (:inherit highlight))))
 '(sp-show-pair-match-face ((((class color) (min-colors 89)) (:foreground "#2aa198" :background "#002b36" :weight normal :inverse-video t))))
 '(sp-show-pair-mismatch-face ((((class color) (min-colors 89)) (:foreground "#dc322f" :background "#002b36" :weight normal :inverse-video t))))
 '(show-paren-match ((((class color) (min-colors 89)) (:foreground "#2aa198" :background "#002b36" :weight normal :inverse-video t))))
 '(show-paren-mismatch ((((class color) (min-colors 89)) (:foreground "#dc322f" :background "#002b36" :weight normal :inverse-video t))))
 '(paren-face-match ((((class color) (min-colors 89)) (:foreground "#2aa198" :background "#002b36" :weight normal :inverse-video t))))
 '(paren-face-mismatch ((((class color) (min-colors 89)) (:foreground "#dc322f" :background "#002b36" :weight normal :inverse-video t))))
 '(paren-face-no-match ((((class color) (min-colors 89)) (:foreground "#dc322f" :background "#002b36" :weight normal :inverse-video t))))
 '(slime-repl-inputed-output-face ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(speedbar-button-face ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#586e75"))))
 '(speedbar-directory-face ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#268bd2"))))
 '(speedbar-file-face ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#839496"))))
 '(speedbar-highlight-face ((((class color) (min-colors 89)) (:inherit variable-pitch :background "#073642"))))
 '(speedbar-selected-face ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#b58900" :underline t))))
 '(speedbar-separator-face ((((class color) (min-colors 89)) (:inherit variable-pitch :background "#268bd2" :foreground "#002b36" :overline "#00736F"))))
 '(speedbar-tag-face ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#859900"))))
 '(sr-active-path-face ((((class color) (min-colors 89)) (:background "#268bd2" :foreground "#002b36" :height 100 :weight bold))))
 '(sr-editing-path-face ((((class color) (min-colors 89)) (:background "#b58900" :foreground "#002b36" :weight bold :height 100))))
 '(sr-highlight-path-face ((((class color) (min-colors 89)) (:background "#859900" :foreground "#002b36" :weight bold :height 100))))
 '(sr-passive-path-face ((((class color) (min-colors 89)) (:background "#586e75" :foreground "#002b36" :weight bold :height 100))))
 '(sr-marked-dir-face ((((class color) (min-colors 89)) (:inherit dired-marked))))
 '(sr-marked-file-face ((((class color) (min-colors 89)) (:inherit dired-marked))))
 '(sr-alt-marked-dir-face ((((class color) (min-colors 89)) (:background "#d33682" :foreground "#002b36" :weight bold))))
 '(sr-alt-marked-file-face ((((class color) (min-colors 89)) (:background "#d33682" :foreground "#002b36" :weight bold))))
 '(sr-directory-face ((((class color) (min-colors 89)) (:inherit dired-directory :weight normal))))
 '(sr-symlink-directory-face ((((class color) (min-colors 89)) (:inherit dired-directory :slant italic :weight normal))))
 '(sr-symlink-face ((((class color) (min-colors 89)) (:inherit dired-symlink :slant italic :weight normal))))
 '(sr-broken-link-face ((((class color) (min-colors 89)) (:inherit dired-warning :slant italic :weight normal))))
 '(sr-compressed-face ((((class color) (min-colors 89)) (:foreground "#839496"))))
 '(sr-encrypted-face ((((class color) (min-colors 89)) (:foreground "#839496"))))
 '(sr-log-face ((((class color) (min-colors 89)) (:foreground "#839496"))))
 '(sr-packaged-face ((((class color) (min-colors 89)) (:foreground "#839496"))))
 '(sr-html-face ((((class color) (min-colors 89)) (:foreground "#839496"))))
 '(sr-xml-face ((((class color) (min-colors 89)) (:foreground "#839496"))))
 '(sr-clex-hotchar-face ((((class color) (min-colors 89)) (:background "#dc322f" :foreground "#002b36" :weight bold))))
 '(table-cell ((((class color) (min-colors 89)) (:foreground "#839496" :background "#073642"))))
 '(term-color-black ((t (:foreground "#002b36" :background "#073642"))))
 '(term-color-red ((t (:foreground "#dc322f" :background "#990A1B"))))
 '(term-color-green ((t (:foreground "#859900" :background "#546E00"))))
 '(term-color-yellow ((t (:foreground "#b58900" :background "#7B6000"))))
 '(term-color-blue ((t (:foreground "#268bd2" :background "#00629D"))))
 '(term-color-magenta ((t (:foreground "#d33682" :background "#93115C"))))
 '(term-color-cyan ((t (:foreground "#2aa198" :background "#00736F"))))
 '(term-color-white ((t (:foreground "#657b83" :background "#839496"))))
 '(term-default-fg-color ((t (:inherit term-color-white))))
 '(term-default-bg-color ((t (:inherit term-color-black))))
 '(tooltip ((((class color) (min-colors 89)) (:background "#7B6000" :foreground "#DEB542" :inherit variable-pitch))))
 '(tuareg-font-lock-governing-face ((((class color) (min-colors 89)) (:foreground "#d33682" :weight bold))))
 '(tuareg-font-lock-multistage-face ((((class color) (min-colors 89)) (:foreground "#268bd2" :background "#073642" :weight bold))))
 '(tuareg-font-lock-operator-face ((((class color) (min-colors 89)) (:foreground "#93a1a1"))))
 '(tuareg-font-lock-error-face ((((class color) (min-colors 89)) (:foreground "#b58900" :background "#dc322f" :weight bold))))
 '(tuareg-font-lock-interactive-output-face ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(tuareg-font-lock-interactive-error-face ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(undo-tree-visualizer-default-face ((((class color) (min-colors 89)) (:foreground "#586e75" :background "#002b36"))))
 '(undo-tree-visualizer-unmodified-face ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(undo-tree-visualizer-current-face ((((class color) (min-colors 89)) (:foreground "#268bd2" :inverse-video t))))
 '(undo-tree-visualizer-active-branch-face ((((class color) (min-colors 89)) (:foreground "#93a1a1" :background "#002b36" :weight bold))))
 '(undo-tree-visualizer-register-face ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(vhl/default-face ((((class color) (min-colors 89)) (:background "#546E00" :foreground "#B4C342"))))
 '(w3m-anchor ((((class color) (min-colors 89)) (:inherit link))))
 '(w3m-arrived-anchor ((((class color) (min-colors 89)) (:inherit link-visited))))
 '(w3m-form ((((class color) (min-colors 89)) (:background "#002b36" :foreground "#839496"))))
 '(w3m-header-line-location-title ((((class color) (min-colors 89)) (:background "#073642" :foreground "#b58900"))))
 '(w3m-header-line-location-content ((((class color) (min-colors 89)) (:background "#073642" :foreground "#839496"))))
 '(w3m-bold ((((class color) (min-colors 89)) (:foreground "#93a1a1" :weight bold))))
 '(w3m-image-anchor ((((class color) (min-colors 89)) (:background "#002b36" :foreground "#2aa198" :inherit link))))
 '(w3m-image ((((class color) (min-colors 89)) (:background "#002b36" :foreground "#2aa198"))))
 '(w3m-lnum-minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#93a1a1"))))
 '(w3m-lnum-match ((((class color) (min-colors 89)) (:background "#073642"))))
 '(w3m-lnum ((((class color) (min-colors 89)) (:underline nil :bold nil :foreground "#dc322f"))))
 '(w3m-session-select ((((class color) (min-colors 89)) (:foreground "#839496"))))
 '(w3m-session-selected ((((class color) (min-colors 89)) (:foreground "#93a1a1" :bold t :underline t))))
 '(w3m-tab-background ((((class color) (min-colors 89)) (:background "#002b36" :foreground "#839496"))))
 '(w3m-tab-selected-background ((((class color) (min-colors 89)) (:background "#002b36" :foreground "#839496"))))
 '(w3m-tab-mouse ((((class color) (min-colors 89)) (:background "#073642" :foreground "#b58900"))))
 '(w3m-tab-selected ((((class color) (min-colors 89)) (:background "#073642" :foreground "#93a1a1" :bold t))))
 '(w3m-tab-unselected ((((class color) (min-colors 89)) (:background "#073642" :foreground "#839496"))))
 '(w3m-tab-selected-retrieving ((((class color) (min-colors 89)) (:background "#073642" :foreground "#dc322f"))))
 '(w3m-tab-unselected-retrieving ((((class color) (min-colors 89)) (:background "#073642" :foreground "#cb4b16"))))
 '(w3m-tab-unselected-unseen ((((class color) (min-colors 89)) (:background "#073642" :foreground "#6c71c4"))))
 '(web-mode-builtin-face ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(web-mode-comment-face ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(web-mode-constant-face ((((class color) (min-colors 89)) (:foreground "#268bd2" :weight bold))))
 '(web-mode-css-at-rule-face ((((class color) (min-colors 89)) (:foreground "#6c71c4" :slant italic))))
 '(web-mode-css-prop-face ((((class color) (min-colors 89)) (:foreground "#6c71c4"))))
 '(web-mode-css-pseudo-class-face ((((class color) (min-colors 89)) (:foreground "#859900" :slant italic))))
 '(web-mode-css-rule-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(web-mode-doctype-face ((((class color) (min-colors 89)) (:foreground "#586e75" :slant italic :weight bold))))
 '(web-mode-folded-face ((((class color) (min-colors 89)) (:underline t))))
 '(web-mode-function-name-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(web-mode-html-attr-name-face ((((class color) (min-colors 89)) (:foreground "#268bd2" :slant normal))))
 '(web-mode-html-attr-value-face ((((class color) (min-colors 89)) (:foreground "#2aa198" :slant italic))))
 '(web-mode-html-tag-face ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(web-mode-keyword-face ((((class color) (min-colors 89)) (:foreground "#b58900" :weight bold))))
 '(web-mode-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#b58900" :slant italic :weight bold))))
 '(web-mode-string-face ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(web-mode-type-face ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(web-mode-variable-name-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(web-mode-server-background-face ((((class color) (min-colors 89)) (:background "#002b36"))))
 '(web-mode-server-comment-face ((((class color) (min-colors 89)) (:inherit web-mode-comment-face))))
 '(web-mode-server-string-face ((((class color) (min-colors 89)) (:inherit web-mode-string-face))))
 '(web-mode-warning-face ((((class color) (min-colors 89)) (:inherit font-lock-warning-face))))
 '(web-mode-whitespaces-face ((((class color) (min-colors 89)) (:background "#dc322f"))))
 '(whitespace-space ((((class color) (min-colors 89)) (:background unspecified :foreground "#586e75" :inverse-video unspecified :slant italic))))
 '(whitespace-hspace ((((class color) (min-colors 89)) (:background unspecified :foreground "#93a1a1" :inverse-video unspecified))))
 '(whitespace-tab ((((class color) (min-colors 89)) (:background unspecified :foreground "#dc322f" :inverse-video unspecified :weight bold))))
 '(whitespace-newline ((((class color) (min-colors 89)) (:background unspecified :foreground "#586e75" :inverse-video unspecified))))
 '(whitespace-trailing ((((class color) (min-colors 89)) (:background unspecified :foreground "#8B2C02" :inverse-video t))))
 '(whitespace-line ((((class color) (min-colors 89)) (:background unspecified :foreground "#d33682" :inverse-video unspecified))))
 '(whitespace-space-before-tab ((((class color) (min-colors 89)) (:background "#990A1B" :foreground unspecified :inverse-video unspecified))))
 '(whitespace-indentation ((((class color) (min-colors 89)) (:background unspecified :foreground "#b58900" :inverse-video unspecified :weight bold))))
 '(whitespace-empty ((((class color) (min-colors 89)) (:background unspecified :foreground "#990A1B" :inverse-video t))))
 '(whitespace-space-after-tab ((((class color) (min-colors 89)) (:background unspecified :foreground "#cb4b16" :inverse-video t :weight bold))))
 '(wl-highlight-folder-few-face ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(wl-highlight-folder-many-face ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(wl-highlight-folder-path-face ((((class color) (min-colors 89)) (:foreground "#cb4b16"))))
 '(wl-highlight-folder-unread-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(wl-highlight-folder-zero-face ((((class color) (min-colors 89)) (:foreground "#839496"))))
 '(wl-highlight-folder-unknown-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(wl-highlight-message-citation-header ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(wl-highlight-message-cited-text-1 ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(wl-highlight-message-cited-text-2 ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(wl-highlight-message-cited-text-3 ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(wl-highlight-message-cited-text-4 ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(wl-highlight-message-header-contents-face ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(wl-highlight-message-headers-face ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(wl-highlight-message-important-header-contents ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(wl-highlight-message-header-contents ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(wl-highlight-message-important-header-contents2 ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(wl-highlight-message-signature ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(wl-highlight-message-unimportant-header-contents ((((class color) (min-colors 89)) (:foreground "#839496"))))
 '(wl-highlight-summary-answered-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(wl-highlight-summary-disposed-face ((((class color) (min-colors 89)) (:foreground "#839496" :slant italic))))
 '(wl-highlight-summary-new-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(wl-highlight-summary-normal-face ((((class color) (min-colors 89)) (:foreground "#839496"))))
 '(wl-highlight-summary-thread-top-face ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(wl-highlight-thread-indent-face ((((class color) (min-colors 89)) (:foreground "#d33682"))))
 '(wl-highlight-summary-refiled-face ((((class color) (min-colors 89)) (:foreground "#839496"))))
 '(wl-highlight-summary-displaying-face ((((class color) (min-colors 89)) (:underline t :weight bold))))
 '(weechat-error-face ((((class color) (min-colors 89)) (:inherit error))))
 '(weechat-highlight-face ((((class color) (min-colors 89)) (:foreground "#93a1a1" :weight bold))))
 '(weechat-nick-self-face ((((class color) (min-colors 89)) (:foreground "#859900" :weight unspecified :inverse-video t))))
 '(weechat-prompt-face ((((class color) (min-colors 89)) (:inherit minibuffer-prompt))))
 '(weechat-time-face ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(which-func ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(window-number-face ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(yascroll:thumb-text-area ((((class color) (min-colors 89)) (:foreground "#586e75" :background "#586e75"))))
 '(yascroll:thumb-fringe ((((class color) (min-colors 89)) (:foreground "#586e75" :background "#586e75"))))
 '(zencoding-preview-input ((((class color) (min-colors 89)) (:background "#073642" :box "#93a1a1"))))
 '(default ((t (:background "#002b36" :foreground "snow")))))

(provide-theme 'mgualt-solarized-dark)
